version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.20.0
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:btZIX7MqhgzEtJuohV23iAoUmXiLcdWHknRt0O4gdNc"
      - checkout
      - run: 
          name: List directory contents
          command: |
            echo "Project root:"
            ls -la
            echo "SimpleApplication directory:"
            ls -la SimpleApplication || echo "No SimpleApplication directory found"
      - run: 
          name: Install Dependencies
          command: |
            cd SimpleApplication
            npm ci
      - run: 
          name: Run Tests
          command: |
            cd SimpleApplication
            npm test
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:btZIX7MqhgzEtJuohV23iAoUmXiLcdWHknRt0O4gdNc"
      - run:
          name: Deploy to EC2
          command: |
            ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $EC2_USERNAME@$EC2_PUBLIC_IP "cd ~/devops-ca/SimpleApplication && git pull origin main"
            ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $EC2_USERNAME@$EC2_PUBLIC_IP "cd ~/devops-ca/SimpleApplication && npm install"
            ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $EC2_USERNAME@$EC2_PUBLIC_IP "cd ~/devops-ca/SimpleApplication && pm2 describe mathapp > /dev/null && if [ \$? -eq 0 ]; then pm2 restart mathapp; else SSL_KEY_PATH=~/devops-ca/SimpleApplication/privatekey.pem SSL_CERT_PATH=~/devops-ca/SimpleApplication/server.crt pm2 start ./bin/www --name mathapp; fi"
            ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $EC2_USERNAME@$EC2_PUBLIC_IP "pm2 save"
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main