version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0

jobs:
  build:
    docker:
      - image: cimg/node:14.20.0
    steps:
      - checkout
      - run:
          name: List Directory Contents
          command: |
            echo "Current directory:"
            pwd
            echo "Directory contents:"
            ls -la
            echo "SimpleApplication contents:"
            ls -la SimpleApplication
      - run:
          name: Install Dependencies
          command: |
            cd SimpleApplication
            npm install
      - run:
          name: Run Tests
          command: |
            cd SimpleApplication
            npm test

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - aws-cli/setup
      - add_ssh_keys:
          fingerprints:
            - "SHA256:btZIX7MqhgzEtJuohV23iAoUmXiLcdWHknRt0O4gdNc"
      - run:
          name: Deploy to EC2
          command: |
            ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS '
            cd ~/devops-ca/SimpleApplication &&
            git pull origin main &&
            npm install &&
            pm2 start ./bin/www --name mathapp || pm2 restart mathapp
            '

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main