version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0

jobs:
  build:
    docker:
      - image: cimg/node:14.20.0
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            cd SimpleApplication
            npm install
      - run:
          name: Run Tests
          command: |
            cd SimpleApplication
            npm test

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - aws-cli/setup
      - add_ssh_keys:
          fingerprints:
            - "SHA256:btZIX7MqhgzEtJuohV23iAoUmXiLcdWHknRt0O4gdNc"
      - run:
          name: Deploy to EC2
          no_output_timeout: 30m
          command: |
            if [ -z "$EC2_PUBLIC_IP" ]; then
              echo "EC2_PUBLIC_IP is not set. Please set this environment variable in CircleCI project settings."
              exit 1
            fi
            echo "Attempting to connect to $EC2_PUBLIC_IP"
            ssh -v -o StrictHostKeyChecking=no -o ConnectTimeout=10 $EC2_USERNAME@$EC2_PUBLIC_IP '
            set -ex
            echo "Successfully connected to EC2 instance"
            echo "Current directory: $(pwd)"
            
            # Check if Node.js is installed
            if ! command -v node &> /dev/null; then
              echo "Node.js not found. Installing Node.js and npm..."
              curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi
            
            # Verify Node.js and npm installation
            node --version
            npm --version
            
            # Create directory if it doesnt exist
            mkdir -p ~/devops-ca/SimpleApplication
            
            # Navigate to the directory
            cd ~/devops-ca/SimpleApplication
            
            # Check if the repository is already cloned
            if [ ! -d ".git" ]; then
              echo "Cloning repository..."
              git clone https://github.com/sumafujiko/devops-ca.git .
            else
              echo "Pulling latest changes..."
              git pull origin main
            fi
            
            echo "Installing dependencies..."
            npm install
            
            # Check if PM2 is installed globally, if not install it
            if ! command -v pm2 &> /dev/null; then
              echo "PM2 not found. Installing PM2..."
              sudo npm install -g pm2
            fi
            
            echo "Starting/Restarting application..."
            pm2 start ./bin/www --name mathapp || pm2 restart mathapp
            
            echo "Deployment completed successfully"
            '

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main